project_id = "lavqzqqfsdtduwphzehr"

[functions.webhook-asaas]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-enrollment-checkout]
verify_jwt = false

[functions.create-discounted-checkout]
verify_jwt = false

[functions.generate-enrollment-documents]
verify_jwt = true

[functions.generate-course-image]
verify_jwt = true

[functions.generate-course-image-v2]
verify_jwt = true

[functions.check-certificate-availability]
verify_jwt = false

[functions.test-gemini-api-key]
verify_jwt = false

[functions.call-discount-webhook]
verify_jwt = false
